package scoreWriter;

public enum SymbolId {
    // CLEF
    CLEF_TREBLE,
    CLEF_TREBLE_8,
    CLEF_BASS,

    // NOTES
    WHOLE_NOTE,
    HALF_NOTE,
    QUARTER_NOTE,
    EIGHTH_NOTE,
    SIXTEENTH_NOTE,
    THIRTY_SECOND_NOTE,
    SIXTY_FOURTH_NOTE,

    // RESTS
    WHOLE_REST,
    HALF_REST,
    QUARTER_REST,
    EIGHTH_REST,
    SIXTEENTH_REST,
    THIRTY_SECOND_REST,
    SIXTY_FOURTH_REST,

    // BARLINES
    BARLINE_SINGLE,
    BARLINE_DOUBLE,
    BARLINE_FINAL,
    BARLINE_REPEAT_START,
    BARLINE_REPEAT_END
}
